### ISSUE TITLE
UX: Recovery mnemonic is not copy-pastable in ShowMnemonic

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#13]
Text isn't selectable because of
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/pages/ShowMnemonic/index.js#L40-L47
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/App.scss#L22-L29
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/App.scss#L3-L5

so e.g. this would allow selection
```css
.mne-container,
.mne-container .mne-item {
  user-select: all;
}
```

or displaying it in a textarea like RevealSeedPage
